/*
 *   Copyright (c) 2026 qecko-labs
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package contribute

import (
	"bytes"
	"context"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/forgezero-cli/ForgeZero/internal/doctor"
)

type ContributeReport struct {
	Status           string   `json:"status"`
	Errors           []string `json:"errors,omitempty"`
	EnvironmentCheck struct {
		Healthy bool     `json:"healthy"`
		Details []string `json:"details,omitempty"`
	} `json:"environment_check"`
	Tests struct {
		Suggested []string `json:"suggested"`
	} `json:"tests"`
	Build struct {
		Suggested []string `json:"suggested"`
	} `json:"build"`
	GoodFirstIssues struct {
		Suggested []string `json:"suggested"`
	} `json:"good_first_issues"`
	Mentoring struct {
		Suggestions []string `json:"suggestions"`
	} `json:"mentoring"`
}

func Run(ctx context.Context, rootDir string) (ContributeReport, error) {
	var rep ContributeReport
	rep.Status = "ok"

	if strings.TrimSpace(rootDir) == "" {
		var err error
		rootDir, err = os.Getwd()
		if err != nil {
			return rep, err
		}
	}

	doc, err := doctor.Run(ctx, doctor.Options{Root: rootDir})
	if err != nil {
		rep.EnvironmentCheck.Healthy = false
		rep.EnvironmentCheck.Details = append(rep.EnvironmentCheck.Details, "doctor error: "+err.Error())
		rep.Errors = append(rep.Errors, err.Error())
	} else {
		rep.EnvironmentCheck.Healthy = doc.Healthy
		for _, tc := range doc.Toolchain {
			rep.EnvironmentCheck.Details = append(rep.EnvironmentCheck.Details,
				"toolchain: "+tc.Name+" required="+boolStr(tc.Required)+" found="+boolStr(tc.Found)+" path="+tc.Path)
		}
		rep.EnvironmentCheck.Details = append(rep.EnvironmentCheck.Details,
			"permissions: readable="+boolStr(doc.Permissions.Readable)+" writable="+boolStr(doc.Permissions.Writable)+" root="+doc.Permissions.Root,
			"platform: "+doc.Platform.GOOS+"/"+doc.Platform.GOARCH)
	}

	rep.Tests.Suggested = suggestTests(rootDir)
	rep.Build.Suggested = suggestBuild(rootDir)
	rep.GoodFirstIssues.Suggested = suggestGoodFirstIssues(rootDir)
	rep.Mentoring.Suggestions = suggestMentoring(rootDir)

	if err := writeContributingUserMD(rootDir, rep); err != nil {
		return rep, err
	}

	return rep, nil
}

func boolStr(b bool) string {
	if b {
		return "true"
	}
	return "false"
}

func suggestTests(rootDir string) []string {
	var out []string
	if _, err := os.Stat(filepath.Join(rootDir, "go.mod")); err == nil {
		out = append(out, "go test ./...")
		out = append(out, "go test -race ./...")
	}
	return uniqueSorted(out)
}

func suggestBuild(rootDir string) []string {
	var out []string
	if _, err := os.Stat(filepath.Join(rootDir, "go.mod")); err == nil {
		out = append(out, "go build ./cmd/fz")
		out = append(out, "go build -o ./bin/fz ./cmd/fz")
	}
	out = append(out, "fz -dir ./src -out ./bin/forgezero")
	return uniqueSorted(out)
}

func suggestGoodFirstIssues(rootDir string) []string {
	var out []string
	var todoFiles []string

	if err := filepath.WalkDir(rootDir, func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			base := filepath.Base(p)
			if base == ".git" || base == "vendor" || base == "bin" {
				return filepath.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(p, ".go") || strings.Contains(p, "_test.go") {
			return nil
		}
		data, err := os.ReadFile(p)
		if err != nil {
			return nil
		}
		if strings.Contains(string(data), "TODO") || strings.Contains(string(data), "FIXME") {
			todoFiles = append(todoFiles, p)
		}
		return nil
	}); err != nil {
		return nil
	}

	sort.Strings(todoFiles)
	for i := 0; i < len(todoFiles) && i < 6; i++ {
		rel, _ := filepath.Rel(rootDir, todoFiles[i])
		out = append(out, "Triage TODO/FIXME in "+rel)
	}

	if _, err := os.Stat(filepath.Join(rootDir, "README.md")); err == nil {
		out = append(out, "Improve README documentation")
	}

	return uniqueSorted(out)
}

func suggestMentoring(rootDir string) []string {
	out := []string{
		"Review design invariants in internal packages",
		"Add tests around CLI flag handling",
	}
	return uniqueSorted(out)
}

func writeContributingUserMD(rootDir string, rep ContributeReport) error {
	outPath := filepath.Join(rootDir, "CONTRIBUTING_USER.md")
	var b bytes.Buffer

	b.WriteString("# Contributing (Generated by ForgeZero)\n\n")
	b.WriteString("Generated: ")
	b.WriteString(time.Now().UTC().Format(time.RFC3339))
	b.WriteString("\n\n")

	b.WriteString("## Environment check\n\n")
	if rep.EnvironmentCheck.Healthy {
		b.WriteString("- Status: healthy\n")
	} else {
		b.WriteString("- Status: not healthy\n")
	}
	for _, d := range rep.EnvironmentCheck.Details {
		b.WriteString("- ")
		b.WriteString(d)
		b.WriteString("\n")
	}

	b.WriteString("\n## Running tests\n\n")
	for _, s := range rep.Tests.Suggested {
		b.WriteString("- `")
		b.WriteString(s)
		b.WriteString("`\n")
	}

	b.WriteString("\n## Local build\n\n")
	for _, s := range rep.Build.Suggested {
		b.WriteString("- `")
		b.WriteString(s)
		b.WriteString("`\n")
	}

	b.WriteString("\n## Good first issues\n\n")
	for _, s := range rep.GoodFirstIssues.Suggested {
		b.WriteString("- ")
		b.WriteString(s)
		b.WriteString("\n")
	}

	b.WriteString("\n## Mentoring mode\n\n")
	for _, s := range rep.Mentoring.Suggestions {
		b.WriteString("- ")
		b.WriteString(s)
		b.WriteString("\n")
	}

	b.WriteString("\n## PR guidelines\n\n")
	b.WriteString("- Use imperative descriptive titles\n")
	b.WriteString("- Keep commits small and focused\n")
	b.WriteString("- Run `go test ./...` before opening PR\n")

	return os.WriteFile(outPath, b.Bytes(), 0o644)
}

func uniqueSorted(in []string) []string {
	seen := make(map[string]struct{}, len(in))
	out := make([]string, 0, len(in))
	for _, s := range in {
		s = strings.TrimSpace(s)
		if s == "" {
			continue
		}
		if _, ok := seen[s]; !ok {
			seen[s] = struct{}{}
			out = append(out, s)
		}
	}
	sort.Strings(out)
	return out
}
