/*
 *   Copyright (c) 2026 qecko-labs
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package contribute

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestRunCreatesContributingUserMD(t *testing.T) {
	tmpDir := t.TempDir()
	ctx := context.Background()

	report, err := Run(ctx, tmpDir)
	if err != nil {
		t.Fatalf("Run failed: %v", err)
	}

	if report.Status != "ok" {
		t.Errorf("expected status ok, got %s", report.Status)
	}

	outputPath := filepath.Join(tmpDir, "CONTRIBUTING_USER.md")
	if _, err := os.Stat(outputPath); os.IsNotExist(err) {
		t.Fatalf("CONTRIBUTING_USER.md not created")
	}

	data, err := os.ReadFile(outputPath)
	if err != nil {
		t.Fatalf("cannot read output: %v", err)
	}
	content := string(data)

	expectedSections := []string{
		"# Contributing (Generated by ForgeZero)",
		"## Environment check",
		"## Running tests",
		"## Local build",
		"## Good first issues",
		"## Mentoring mode",
		"## PR guidelines",
	}
	for _, section := range expectedSections {
		if !strings.Contains(content, section) {
			t.Errorf("missing section: %s", section)
		}
	}
}

func TestRunWithGoModSuggestsGoCommands(t *testing.T) {
	tmpDir := t.TempDir()
	ctx := context.Background()

	goModPath := filepath.Join(tmpDir, "go.mod")
	if err := os.WriteFile(goModPath, []byte("module test\n"), 0644); err != nil {
		t.Fatalf("cannot create go.mod: %v", err)
	}

	report, err := Run(ctx, tmpDir)
	if err != nil {
		t.Fatalf("Run failed: %v", err)
	}

	foundGoTest := false
	foundGoBuild := false
	for _, s := range report.Tests.Suggested {
		if strings.Contains(s, "go test") {
			foundGoTest = true
		}
	}
	for _, s := range report.Build.Suggested {
		if strings.Contains(s, "go build") {
			foundGoBuild = true
		}
	}

	if !foundGoTest {
		t.Errorf("expected go test suggestions, got %v", report.Tests.Suggested)
	}
	if !foundGoBuild {
		t.Errorf("expected go build suggestions, got %v", report.Build.Suggested)
	}
}

func TestRunWithoutGoMod(t *testing.T) {
	tmpDir := t.TempDir()
	ctx := context.Background()

	report, err := Run(ctx, tmpDir)
	if err != nil {
		t.Fatalf("Run failed: %v", err)
	}

	for _, s := range report.Tests.Suggested {
		if strings.Contains(s, "go test") {
			t.Errorf("go test suggested without go.mod: %s", s)
		}
	}
}

func TestRunWithTodoFiles(t *testing.T) {
	tmpDir := t.TempDir()
	ctx := context.Background()

	srcDir := filepath.Join(tmpDir, "internal", "test")
	if err := os.MkdirAll(srcDir, 0755); err != nil {
		t.Fatalf("cannot create dir: %v", err)
	}

	todoContent := []byte("package test\n\n// TODO: implement this\nfunc Foo() {}\n")
	todoPath := filepath.Join(srcDir, "todo.go")
	if err := os.WriteFile(todoPath, todoContent, 0644); err != nil {
		t.Fatalf("cannot write todo.go: %v", err)
	}

	report, err := Run(ctx, tmpDir)
	if err != nil {
		t.Fatalf("Run failed: %v", err)
	}

	found := false
	for _, s := range report.GoodFirstIssues.Suggested {
		if strings.Contains(s, "TODO") || strings.Contains(s, "FIXME") {
			found = true
		}
	}
	if !found {
		t.Errorf("expected TODO/FIXME suggestion, got %v", report.GoodFirstIssues.Suggested)
	}
}

func TestRunWithEmptyRootDir(t *testing.T) {
	ctx := context.Background()

	report, err := Run(ctx, "")
	if err != nil {
		t.Fatalf("Run with empty root failed: %v", err)
	}
	if report.Status != "ok" {
		t.Errorf("expected status ok, got %s", report.Status)
	}
}

func TestUniqueSorted(t *testing.T) {
	input := []string{"b", "a", "c", "a", "b", "c"}
	expected := []string{"a", "b", "c"}

	result := uniqueSorted(input)
	if len(result) != len(expected) {
		t.Fatalf("expected len %d, got %d", len(expected), len(result))
	}
	for i := range expected {
		if result[i] != expected[i] {
			t.Errorf("at index %d: expected %s, got %s", i, expected[i], result[i])
		}
	}
}

func TestUniqueSortedEmpty(t *testing.T) {
	result := uniqueSorted([]string{})
	if len(result) != 0 {
		t.Errorf("expected empty slice, got %v", result)
	}
}

func TestUniqueSortedWithEmptyStrings(t *testing.T) {
	input := []string{"", "a", "", "b", ""}
	expected := []string{"a", "b"}

	result := uniqueSorted(input)
	if len(result) != len(expected) {
		t.Fatalf("expected len %d, got %d", len(expected), len(result))
	}
	for i := range expected {
		if result[i] != expected[i] {
			t.Errorf("at index %d: expected %s, got %s", i, expected[i], result[i])
		}
	}
}
